import React, { useState } from 'react';

import '../index.css';

// DUMMY DATA GENERATED BY GPT FOR TEST PURPOSES
const fetchData = async (report) => {
  switch (report) {
    case "Report 1": // Inventory Report
      return [
        { id: 1, product: "Product A", stock: 50, reorderLevel: 20, supplier: "Supplier X" },
        { id: 2, product: "Product B", stock: 30, reorderLevel: 15, supplier: "Supplier Y" },
        { id: 3, product: "Product C", stock: 20, reorderLevel: 10, supplier: "Supplier Z" },
        { id: 4, product: "Product D", stock: 60, reorderLevel: 25, supplier: "Supplier X" },
        { id: 5, product: "Product E", stock: 40, reorderLevel: 18, supplier: "Supplier Y" },
        { id: 6, product: "Product F", stock: 35, reorderLevel: 17, supplier: "Supplier Z" },
        { id: 7, product: "Product G", stock: 55, reorderLevel: 22, supplier: "Supplier X" },
        { id: 8, product: "Product H", stock: 25, reorderLevel: 12, supplier: "Supplier Y" },
        { id: 9, product: "Product I", stock: 45, reorderLevel: 21, supplier: "Supplier Z" },
        { id: 10, product: "Product J", stock: 33, reorderLevel: 16, supplier: "Supplier X" },
        { id: 11, product: "Product K", stock: 28, reorderLevel: 14, supplier: "Supplier Y" },
        { id: 12, product: "Product L", stock: 48, reorderLevel: 23, supplier: "Supplier Z" },
        { id: 13, product: "Product M", stock: 37, reorderLevel: 18, supplier: "Supplier X" },
        { id: 14, product: "Product N", stock: 29, reorderLevel: 13, supplier: "Supplier Y" },
        { id: 15, product: "Product O", stock: 43, reorderLevel: 19, supplier: "Supplier Z" },
        { id: 16, product: "Product P", stock: 32, reorderLevel: 15, supplier: "Supplier X" },
        { id: 17, product: "Product Q", stock: 22, reorderLevel: 11, supplier: "Supplier Y" },
        { id: 18, product: "Product R", stock: 39, reorderLevel: 20, supplier: "Supplier Z" },
        { id: 19, product: "Product S", stock: 58, reorderLevel: 24, supplier: "Supplier X" },
        { id: 20, product: "Product T", stock: 27, reorderLevel: 16, supplier: "Supplier Y" },
      ];
    case "Report 2": // Orders Report
      return [
        { id: 1, orderNumber: "001", product: "Product A", quantity: 5, total: "$100", status: "Shipped" },
        { id: 2, orderNumber: "002", product: "Product B", quantity: 3, total: "$90", status: "Processing" },
        { id: 3, orderNumber: "003", product: "Product C", quantity: 2, total: "$40", status: "Delivered" },
        { id: 4, orderNumber: "004", product: "Product D", quantity: 4, total: "$120", status: "Processing" },
        { id: 5, orderNumber: "005", product: "Product E", quantity: 6, total: "$180", status: "Shipped" },
        { id: 6, orderNumber: "006", product: "Product F", quantity: 7, total: "$210", status: "Delivered" },
        { id: 7, orderNumber: "007", product: "Product G", quantity: 3, total: "$60", status: "Processing" },
        { id: 8, orderNumber: "008", product: "Product H", quantity: 5, total: "$150", status: "Shipped" },
        { id: 9, orderNumber: "009", product: "Product I", quantity: 2, total: "$50", status: "Delivered" },
        { id: 10, orderNumber: "010", product: "Product J", quantity: 3, total: "$90", status: "Processing" },
        { id: 11, orderNumber: "011", product: "Product K", quantity: 4, total: "$120", status: "Shipped" },
        { id: 12, orderNumber: "012", product: "Product L", quantity: 6, total: "$180", status: "Processing" },
        { id: 13, orderNumber: "013", product: "Product M", quantity: 5, total: "$125", status: "Shipped" },
        { id: 14, orderNumber: "014", product: "Product N", quantity: 3, total: "$90", status: "Delivered" },
        { id: 15, orderNumber: "015", product: "Product O", quantity: 2, total: "$40", status: "Processing" },
        { id: 16, orderNumber: "016", product: "Product P", quantity: 7, total: "$210", status: "Shipped" },
        { id: 17, orderNumber: "017", product: "Product Q", quantity: 4, total: "$100", status: "Delivered" },
        { id: 18, orderNumber: "018", product: "Product R", quantity: 3, total: "$75", status: "Processing" },
        { id: 19, orderNumber: "019", product: "Product S", quantity: 2, total: "$50", status: "Shipped" },
        { id: 20, orderNumber: "020", product: "Product T", quantity: 6, total: "$180", status: "Delivered" },
      ];
    case "Report 3": // Sales Report
      return [
        { id: 1, product: "Product A", unitsSold: 100, totalSales: "$500", averagePrice: "$5" },
        { id: 2, product: "Product B", unitsSold: 60, totalSales: "$270", averagePrice: "$4.5" },
        { id: 3, product: "Product C", unitsSold: 20, totalSales: "$80", averagePrice: "$4" },
        { id: 4, product: "Product D", unitsSold: 80, totalSales: "$400", averagePrice: "$5" },
        { id: 5, product: "Product E", unitsSold: 40, totalSales: "$200", averagePrice: "$5" },
        { id: 6, product: "Product F", unitsSold: 70, totalSales: "$350", averagePrice: "$5" },
        { id: 7, product: "Product G", unitsSold: 30, totalSales: "$120", averagePrice: "$4" },
        { id: 8, product: "Product H", unitsSold: 90, totalSales: "$450", averagePrice: "$5" },
        { id: 9, product: "Product I", unitsSold: 50, totalSales: "$250", averagePrice: "$5" },
        { id: 10, product: "Product J", unitsSold: 65, totalSales: "$325", averagePrice: "$5" },
        { id: 11, product: "Product K", unitsSold: 35, totalSales: "$175", averagePrice: "$5" },
        { id: 12, product: "Product L", unitsSold: 55, totalSales: "$275", averagePrice: "$5" },
        { id: 13, product: "Product M", unitsSold: 25, totalSales: "$125", averagePrice: "$5" },
        { id: 14, product: "Product N", unitsSold: 85, totalSales: "$425", averagePrice: "$5" },
        { id: 15, product: "Product O", unitsSold: 45, totalSales: "$225", averagePrice: "$5" },
        { id: 16, product: "Product P", unitsSold: 75, totalSales: "$375", averagePrice: "$5" },
        { id: 17, product: "Product Q", unitsSold: 15, totalSales: "$75", averagePrice: "$5" },
        { id: 18, product: "Product R", unitsSold: 95, totalSales: "$475", averagePrice: "$5" },
        { id: 19, product: "Product S", unitsSold: 25, totalSales: "$125", averagePrice: "$5" },
        { id: 20, product: "Product T", unitsSold: 80, totalSales: "$400", averagePrice: "$5" },
      ];
    case "Report 4": // Customer Feedback Report
      return [
        { id: 1, feedbackId: "001", comment: "Excellent service!", product: "Product A", rating: "5 stars" },
        { id: 2, feedbackId: "002", comment: "Fast delivery, but packaging could improve.", product: "Product B", rating: "4 stars" },
        { id: 3, feedbackId: "003", comment: "Product C was out of stock, had to wait for restock.", product: "Product C", rating: "3 stars" },
        { id: 4, feedbackId: "004", comment: "Great product quality, exceeded expectations.", product: "Product D", rating: "5 stars" },
        { id: 5, feedbackId: "005", comment: "Average service, nothing extraordinary.", product: "Product E", rating: "3 stars" },
        { id: 6, feedbackId: "006", comment: "Very happy with the purchase, thank you!", product: "Product F", rating: "5 stars" },
        { id: 7, feedbackId: "007", comment: "Good value for money, will buy again.", product: "Product G", rating: "4 stars" },
        { id: 8, feedbackId: "008", comment: "The product arrived damaged, but customer service resolved the issue promptly.", product: "Product H", rating: "3 stars" },
        { id: 9, feedbackId: "009", comment: "Disappointed with the quality, expected better.", product: "Product I", rating: "2 stars" },
        { id: 10, feedbackId: "010", comment: "Product arrived late, missed the occasion.", product: "Product J", rating: "1 star" },
        { id: 11, feedbackId: "011", comment: "Product didn't match the description, misleading.", product: "Product K", rating: "2 stars" },
        { id: 12, feedbackId: "012", comment: "The packaging was torn, product was exposed.", product: "Product L", rating: "3 stars" },
        { id: 13, feedbackId: "013", comment: "Impressed with the quick delivery, received it sooner than expected.", product: "Product M", rating: "5 stars" },
        { id: 14, feedbackId: "014", comment: "The product is exactly as described, very satisfied.", product: "Product N", rating: "5 stars" },
        { id: 15, feedbackId: "015", comment: "Average experience, nothing special.", product: "Product O", rating: "3 stars" },
        { id: 16, feedbackId: "016", comment: "The product broke after a few uses, disappointed.", product: "Product P", rating: "2 stars" },
        { id: 17, feedbackId: "017", comment: "Excellent customer service, they went above and beyond to assist.", product: "Product Q", rating: "5 stars" },
        { id: 18, feedbackId: "018", comment: "The product is good quality for the price.", product: "Product R", rating: "4 stars" },
        { id: 19, feedbackId: "019", comment: "Product arrived damaged, but the refund process was smooth.", product: "Product S", rating: "3 stars" },
        { id: 20, feedbackId: "020", comment: "The product didn't meet expectations, would not recommend.", product: "Product T", rating: "2 stars" },
      ];
    default:
      return [];
  }
};



const ReportPage = () => {
  const [reportSelected, setSelectedReport] = useState('');
  const [dataReport, setReportData] = useState([]);

  const reportChange = (event) => {
    setSelectedReport(event.target.value);
  };

  const generateReport = async () => {
    const data = await fetchData(reportSelected);
    setReportData(data);
  };

  const generateTableHeaders = () => {
    if (dataReport.length > 0) {
      const headers = Object.keys(dataReport[0]);
      return headers.map((header) => <th key={header}>{header}</th>);
    }
    return null;
  };

  const generateTableRows = () => {
    return dataReport.map((item) => (
      <tr key={item.id}>
        {Object.values(item).map((value, index) => (
          <td key={index}>{value}</td>
        ))}
      </tr>
    ));
  };

  return (
    <div className='report-page'>
      <div className="title-container">
        <h1 className="page-title">Report Management</h1>
        <p className="page-description">
          Here you can view and manage various reports related to inventory, orders, and more.
        </p>
      </div>
      <div className='report-selection-container'>
        <select value={reportSelected} onChange={reportChange} className='report-selection-dropdown'>
          <option value="">Select a report</option>
          <option value="Report 1">Report 1</option>
          <option value="Report 2">Report 2</option>
          <option value="Report 3">Report 3</option>
          <option value="Report 4">Report 4</option>
        </select>
        <button onClick={generateReport} className='generate-button'>Generate Report</button>
      </div>
      <div className='report-data-container'>
        {dataReport.length > 0 && (
          <table>
            <thead>
              <tr>{generateTableHeaders()}</tr>
            </thead>
            <tbody>
              {generateTableRows()}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
};


export default ReportPage;

